# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Piráti Praha
email: ondrej.profant@pirati.cz
description: > # this means to ignore newlines until "baseurl:"
    Piráti Praha jsou krajské sdružení Pirátské strany v Praze. Klub Pirátů v zastupitelstvu hl. m. Prahy. Nezávisle kontrolujeme práci vládnoucích politiků. Naši zastupitelé vás informují a hájí!
baseurl: "" # the subpath of your site, e.g. /blog  http://stackoverflow.com/questions/16316311/github-pages-and-relative-paths/19173888#19173888
url: "http://praha.pirati.cz" # the base hostname & protocol for your site

mailchimp:
  newsletter:
    action: https://pirati.us9.list-manage.com/subscribe/post?u=7e063d6dffdb0316b906e1351&amp;id=5b1243a65b
    captcha: b_7e063d6dffdb0316b906e1351_5b1243a65b
  volunters:
    action: https://pirati.us9.list-manage.com/subscribe/post?u=7e063d6dffdb0316b906e1351&amp;id=88a318620c
    captcha: b_7e063d6dffdb0316b906e1351_88a318620c

title_page:
  video: https://www.youtube.com/embed/pWK515EHyG0
  calendar:
    title: https://calendar.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showDate=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=500&amp;wkst=2&amp;hl=cs&amp;bgcolor=%23FFFFFF&amp;src=rm0h4oqjk2j2o0615sc4d1slfk%40group.calendar.google.com&amp;color=%23B1365F&amp;src=lpvmfpogihrca3lqs9p2udae0k%40group.calendar.google.com&amp;color=%238D6F47&amp;ctz=Europe%2FPrague
    praha: https://calendar.google.com/calendar/embed?title=Pir%C3%A1ti%20Praha&amp;showTitle=0&amp;showPrint=0&amp;showTz=0&amp;height=600&amp;wkst=2&amp;hl=cs&amp;bgcolor=%23FFFFFF&amp;src=rm0h4oqjk2j2o0615sc4d1slfk%40group.calendar.google.com&amp;color=%23B1365F&amp;src=lpvmfpogihrca3lqs9p2udae0k%40group.calendar.google.com&amp;color=%238D6F47&amp;ctz=Europe%2FPrague
    magistrat: https://calendar.google.com/calendar/embed?title=Pir%C3%A1ti%20Praha&amp;showTitle=0&amp;showPrint=0&amp;showTz=0&amp;height=600&amp;wkst=2&amp;hl=cs&amp;bgcolor=%23FFFFFF&amp;src=kq1pscnqlcupnugkhslkc8pn0k%40group.calendar.google.com&amp;color=%23853104&amp;src=ts9cg80rgfblibmmgm45keqcl8%40group.calendar.google.com&amp;color=%23853104&amp;ctz=Europe%2FPrague
    global: https://calendar.google.com/calendar/embed?title=Pir%C3%A1ti%20Praha&amp;showTitle=0&amp;showPrint=0&amp;showTz=0&amp;height=600&amp;wkst=2&amp;hl=cs&amp;bgcolor=%23FFFFFF&amp;src=kddvdvu3adcjef2kro4j6mm838%40group.calendar.google.com&amp;color=%232952A3&amp;ctz=Europe%2FPrague
    pice: https://www.google.com/calendar/embed?showCalendars=0&amp;mode=AGENDA&amp;height=600&amp;wkst=2&amp;bgcolor=%23FFFFFF&amp;src=evhpcc3i4hgjut142ru0tn7gl0%40group.calendar.google.com&amp;color=%23182C57&amp;ctz=Europe%2FPrague

permalink: /:title.html
collections:
  people:
    output: true
    permalink: /lide/:path/
  projects:
    output: true
    permalink: /pripoj-se/:path/


gems:
  - jekyll-paginate
paginate_path: "/blog/:num/"
paginate: 12

# Build settings
markdown: kramdown

cdn: true
