title: Pirátská strana Praha
email: to@pirati.cz
description: Prosazujeme fungující moderní politiku založenou na využití technologií 21. století pro otevřenou demokratickou společnost.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://praha.pirati.cz" # the base hostname & protocol for your site

administrator:
  email: jitka.novotna@pirati.cz # mail kam pujdou chybove vystupy


organization:
  name: Pirátká strana Praha
  shortName: Piráti Praha
  contactUid: michal.jokes
  email: kodo-praha@pirati.cz
  phone: +420 770 113 642
  address: |
    Řehořova 943/19,
    130 00 Praha 3
  residenceImg:
  mapLink: https://mapy.cz/zakladni?vlastni-body&x=14.4418976&y=50.0863156&z=18&ut=PiCe&uc=9h2F.xXwtn&ud=ulice%20%C5%98eho%C5%99ova%20943%2F19%2C%20Praha%2C%20130%2000%2C%20okres%20Hlavn%C3%AD%20m%C4%9Bsto%20Praha
  redmineLink: https://redmine.pirati.cz/projects
  dataBoxId: b2i4r6j
  transparentAccount: 2100048174/2010

calendar:
  apiKey: AIzaSyBdjZxz4r9lPyD3CiSxQa6G3mf47ezI7Ks
  id: rm0h4oqjk2j2o0615sc4d1slfk@group.calendar.google.com
  title: "Celopražský kalendář"
  page: "https://calendar.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showDate=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=500&amp;wkst=2&amp;hl=cs&amp;bgcolor=%23FFFFFF&amp;src=rm0h4oqjk2j2o0615sc4d1slfk%40group.calendar.google.com&amp;color=%23B1365F&amp;src=lpvmfpogihrca3lqs9p2udae0k%40group.calendar.google.com&amp;color=%238D6F47&amp;ctz=Europe%2FPrague"

facebook:
  loadSDK: true
  profilePage: "https://www.facebook.com/piratipraha8/"
  appId: 1526197851008996
markdown: kramdown

twitter:
  loadSDK: true
  profile: piratipraha

instagram:
  profilePage: https://www.instagram.com/pirati.cz/

gplus:
  profilePage: https://plus.google.com/u/0/+piratskastrana

flicker:
  profilePage: https://www.flickr.com/photos/pirati/

forum:
  page: https://forum.pirati.cz/

github:
  url: https://github.com/pirati-web/praha8.pirati.cz/
  branch: master

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
paginate_path: "/aktuality/:num/"
paginate: 11

twitter_username: jekyllrb
github_username:  jekyll

theme: jekyll-theme-pirati
exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - package.json
  - bower.json
  - gulpfile.js
  - node_modules
  - bower_components
  - vendor

sass:
    style: compressed

permalink: /:title.html
collections:
  people:
    output: true
    permalink: /lide/:path/
  program:
    output: true
    permalink: /program/2018/:path/
  candidatelists:
    output: false

defaults:   # defaults values for collection scope
  -
    scope:
      path: "_people"
    values:
      layout: "page"
      rbar:
        - foto
        - people
  -
    scope:
      path: "_teams"
    values:
      layout: "team"
      rbar:
         - team-summary
         - teams-toc
  -
    scope:
      path: "_program"
    values:
      layout: "program-post"
      rbar:
      #         - garant
         - program

calendar:
fb: https://www.facebook.com/CeskaPiratskaStranaPraha/
tw: piratipraha

emptyArray: []

assets:
  source_maps: true
  compression: true
  gzip: false
  plugins:
    css: { autoprefixer: {}}
    img:
      optim:
        jpegoptim:
          strip: all
          max_quality: 80
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
  sources:
    - vendor/bundle/ruby/2.5.0/gems/jekyll-theme-pirati-6.6.1/_sass
    - assets/css
    - assets/fonts
    - assets/video
    - assets/img
    - _sass
